#!/bin/sh

# make zips
sed "s/RUNDATE/$1/g" tbf.xml.template > tbf.xml
/home/ernst/workspace/cpachecker/scripts/benchmark.py --cloudPriority URGENT --read-only-dir / --cloud --cloudMaster localhost --cloudClientHeap 8000 tbf.xml
